name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€

on: [push]
#  on push matlab jab puch gitu tab cahlga 
# echo statand fro print karna 
# job are triger automatically
# And this process how github make maoney 
# they give like 50000 minutes every month free for public repo
# but if you want more then you have to pay them
#github ke pass ek ec2 instance hota hai jaha pe job run hota hai jis par wo code ko run karta hae 

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v4

      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ§ª The workflow is now ready to test your code on the runner."

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - run: echo "ğŸ This job's status is ${{ job.status }}."
